# Generated by Django 3.2.15 on 2022-09-25 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=20)),
                ('low_range', models.FloatField()),
                ('high_range', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('preview_text', models.TextField(max_length=200, verbose_name='Preview Text')),
                ('detail_text', models.TextField(max_length=1000, verbose_name='Description')),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('weather_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wetherType', to='App_Api.weather')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
