# Generated by Django 3.2.15 on 2022-09-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preview_text',
        ),
    ]
