# Generated by Django 3.2.15 on 2022-09-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Api', '0002_remove_product_preview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
